In [2]:
import numpy as np

In [7]:
def shiftLeft(arr): 
    
    for i in range(1, len(arr)): 

        arr[i-1]= arr[i] 
        
    arr[len(arr)-1]= 0 
    
    return arr

arr=np.array([1,2,3,4])

print(shiftLeft(arr))

[2 3 4 0]


In [13]:
def rotateLeft(arr): 
    
    temp=arr[0]
    
    for i in range(1, len(arr)): 

        arr[i-1]= arr[i] 
        
    arr[len(arr)-1]= temp
    
    return arr

arr=np.array([1,2,3,4])

print(rotateLeft(arr))

[2 3 4 1]


In [8]:
def shiftRight(arr): 
    
    for i in range(len(arr)-1, 0, -1):
        arr[i]= arr[i-1] 
    arr[0]=0 
    return arr

arr= np.array([1,2,3,4])
print(shiftRight(arr))


[0 1 2 3]


In [12]:
def rotateRight(arr): 
    temp=arr[len(arr)-1]
    for i in range(len(arr)-1, 0, -1):
        arr[i]= arr[i-1] 
    arr[0]=temp 
    return arr

arr= np.array([1,2,3,4])
print(rotateRight(arr))


[4 1 2 3]


In [17]:
def insert(arr,elm,size,index):
    
    if size==len(arr):
        print('Error')
        
    else:
        for i in range(size,index,-1):
            arr[i]=arr[i-1]
        arr[index]=elm
        
    return arr
                
arr= np.array([1,2,3,4,0,0,0,0])
print(insert(arr,11,4,2))        
        

[ 1  2 11  3  4  0  0  0]


In [21]:
def remove(arr,size,index):
    
    if size==len(arr):
        print('Error')
        
    else:
        for i in range(index+1,size):
            arr[i-1]=arr[i]
        arr[size-1]=0
        
    return arr
                
arr= np.array([1,2,11,3,4,0,0,0,0])
print(remove(arr,5,2))     

[1 2 3 4 0 0 0 0 0]


In [25]:
def reverse_in_place(arr):
    
    j=len(arr)-1 
    for i in range(len(arr)//2): 
        arr[i], arr[j]= arr[j], arr[i] 
      
        j-=1 
    return arr

arr= np.array([1,2,3,4])
print(reverse_in_place(arr))
arr= np.array([1,2,3,4,5])
print(reverse_in_place(arr))


[4 3 2 1]
[5 4 3 2 1]


In [4]:
def print_matrix(m):
    row,col = m.shape
    for i in range(row):
        c = 1
        print('|', end='')
        for j in range(col):
            c += 1
            if(len(str(m[i][j])) == 1):
                print(' ',m[i][j], end = '  |')
                c += 6
            else:
                print(' ',m[i][j], end = ' |')
                c += 6
        print()
        print('-'*(c-col))

In [5]:
def swap_coloumns(m):
    
    r,c=m.shape
    
    for i in range(r):
        for j in range(c//2):
            m[i][j],m[i][c-1-j]=m[i][c-1-j],m[i][j]
            
    return m
    
def swap_rows(m):
    
    r,c=m.shape
    
    for i in range(c):
        for j in range(r//2):
            m[j][i],m[r-1-j][i]=m[r-1-j][i],m[j][i]
            
    return m
    


floor1 = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )



floor2 = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )


print_matrix(floor1)

print('Swapped coloumns:')
print()
ans=swap_coloumns(floor1)
print_matrix(ans)
print('Swapped rows:')
print()
ans1=swap_rows(floor2)
print_matrix(ans1)

|  3  |  8  |  4  |  6  |  1  |
-------------------------------
|  7  |  2  |  1  |  9  |  3  |
-------------------------------
|  9  |  0  |  7  |  5  |  8  |
-------------------------------
|  2  |  1  |  3  |  4  |  0  |
-------------------------------
|  1  |  4  |  2  |  8  |  6  |
-------------------------------
Swapped coloumns:

|  1  |  6  |  4  |  8  |  3  |
-------------------------------
|  3  |  9  |  1  |  2  |  7  |
-------------------------------
|  8  |  5  |  7  |  0  |  9  |
-------------------------------
|  0  |  4  |  3  |  1  |  2  |
-------------------------------
|  6  |  8  |  2  |  4  |  1  |
-------------------------------
Swapped rows:

|  1  |  4  |  2  |  8  |  6  |
-------------------------------
|  2  |  1  |  3  |  4  |  0  |
-------------------------------
|  9  |  0  |  7  |  5  |  8  |
-------------------------------
|  7  |  2  |  1  |  9  |  3  |
-------------------------------
|  3  |  8  |  4  |  6  |  1  |
-------------------------------


In [12]:
def upper_triangle(m):
    
    r,c=m.shape
    
#     for i in range(r):
#         print(m[i][c-1-i])       # code for secondary triangle
            
#     return m
    
    for i in range(r):
        for j in range(i+1,r):
            print(m[j][i])           
    return m





floor = np.array([[ '3' , '8' , '4', '5'],
                  ['7' , '2' , '1', '9' ],
                  ['9' , '0' , '7', '2' ],
                  ['1' , '7' , '3', '4' ]
                  ])


#print_matrix(floor)

print('Swapped coloumns:')
print()
ans=upper_triangle(floor)
print_matrix(ans)


Swapped coloumns:

7
9
1
0
7
3
|  3  |  8  |  4  |  5  |
-------------------------
|  7  |  2  |  1  |  9  |
-------------------------
|  9  |  0  |  7  |  2  |
-------------------------
|  1  |  7  |  3  |  4  |
-------------------------


In [1]:
#Run this cell

class Node:
    def __init__(self,elem,next = None):
        self.elem,self.next = elem,next

def createList(arr):
    head = Node(arr[0])
    tail = head
    for i in range(1,len(arr)):
        newNode = Node(arr[i])
        tail.next = newNode
        tail = newNode
    return head

def printLinkedList(head):
    temp = head
    while temp != None:
        if temp.next != None:
            print(temp.elem, end = '-->')
        else:
            print(temp.elem)
        temp = temp.next
    print()

In [10]:
def reverse_out_place(head):

    new_head=Node(head.elem,None)
    temp=head.next

    while temp!=None:
        n=Node(temp.elem,new_head)
        new_head=n
        temp=temp.next
        
    return new_head


print('==============Test Case 1=============')
head = createList(np.array([13,10,6,20,17]))
print('Array: ', end = ' ')
printLinkedList(head)

ola=reverse_out_place(head)
printLinkedList(ola)



==============Test Case 1=============
Array:  13-->10-->6-->20-->17

17-->20-->6-->10-->13



In [11]:
def reverse_in_place(head):

    new_head=None
    temp=head

    while temp!=None:
        n=temp.next
        temp.next=new_head
        new_head=temp
        temp=n
        
    return new_head


print('==============Test Case 1=============')
head = createList(np.array([13,10,6,20,17]))
print('Array: ', end = ' ')
printLinkedList(head)

ola=reverse_out_place(head)
printLinkedList(ola)

==============Test Case 1=============
Array:  13-->10-->6-->20-->17

17-->20-->6-->10-->13

